"""Initial Migration

Revision ID: 99693e2e9ecd
Revises: 
Create Date: 2022-05-20 04:11:57.076687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99693e2e9ecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('contact', sa.String(), nullable=False))
    op.add_column('user_details', sa.Column('charges', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'charges')
    op.drop_column('user_details', 'contact')
    # ### end Alembic commands ###
